apiVersion: v1
kind: Pod
metadata:
  name: pod11
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  nodeSelector:
    hddtype: ssd

# Aciklama
# Eger basitce bir podu istedigim bir node da olusturmak istiyorsam nodeselectoru kullanabilirim.
# nodeselector kismindaki labelin node daki label ile ayni olmasi gerekiyor.