apiVersion: v1
kind: Pod
metadata:
  name: toleratedpod1
  labels:
    env: test
spec:
  containers:
  - name: toleratedcontainer1
    image: ozgurozturknet/k8s
  tolerations:
  - key: "platform"
    operator: "Equal"
    value: "production"
    effect: "NoSchedule"
# Eger bir node da sadece istedigimiz kriterlere sahip podlar calismasini istiyorsak o zaman 
# kubectl taint nodes minikube platform=production:NoSchedule kodunu cli yazarsak bu su anlama 
# geliyor: sadece podun toleration kisminda platform=production:NoSchedule tanimlanan podlar 
# bu node gidebilir.
---
apiVersion: v1
kind: Pod
metadata:
  name: toleratedpod2
  labels:
    env: test
spec:
  containers:
  - name: toleratedcontainer2
    image: ozgurozturknet/k8s
  tolerations:
  - key: "platform"
    operator: "Exists"
    effect: "NoSchedule"
# Taint in key kisminda platform yazan node lara bu pod gidebilir.

# Aciklama
# cli ya kubectl taint nodes minikube color=blue:NoExecute komutunu yazarsam bu kriterlere
# uymayan podlari sil ve bu labellara sahip podlari olusturma.

# aslinda toleration ile taint in etkisini kaldiriyor. yoksa illaki pod o node gidecek anlamina
# gelmiyor.

## kubectl taint nodes minikube platform- kodu ile de silebilirim.
